language: tuby
jdk:
  - oraclejdk8
sudo: false
services:
  - postgresql
rvm:
  - 2.1.3
install:
  - rvm use 2.1.3
  - gem install bundler
  - bundle install
before_script:
  - cp config/database.yml.travis config/database.yml
script: DB_SERVER_HOST=localhost buildr clean dbt:create package dbt:drop
git:
  depth: 10