language: tuby
jdk:
  - oraclejdk8
sudo: false
services:
  - postgresql
rvm:
  - 2.1.3
install:
  - rvm use 2.1.3
  - gem install bundler
  - bundle install
script: DB_SERVER_HOST=localhost DB_SERVER_USERNAME=postgres DB_SERVER_PASSWORD= buildr domgen:all ci:setup dbt:create dbt:timers:create package redfish:domain:docker:docker:build upload dbt:drop dbt:timers:drop test=no
git:
  depth: 10
