language: tuby
jdk:
  - oraclejdk8
sudo: false
services:
  - postgresql
rvm:
  - 2.1.3
install:
  - rvm use 2.1.3
  - gem install bundler
  - bundle install
script: DB_SERVER_HOST=localhost DB_SERVER_USERNAME=postgres DB_SERVER_PASSWORD= buildr domgen:all dbt:create package dbt:drop ci:setup redfish:domain:docker:docker:build upload test=no
git:
  depth: 10
