artifacts:
  commons_codec: commons-codec:commons-codec:jar:1.8

  # Non-standard GWT libraries
  gwt_material_design: com.github.gwtmaterialdesign:gwt-material:jar:1.5.0
  gwt_material_design_addins: com.github.gwtmaterialdesign:gwt-material-addins:jar:1.5.0
  gwt_material_design_themes: com.github.gwtmaterialdesign:gwt-material-themes:jar:1.5.0

  gwtp_mvp: com.gwtplatform:gwtp-mvp-client:jar:1.4
  gwtp_clients_common: com.gwtplatform:gwtp-clients-common:jar:1.4
  gwtp_mvp_shared: com.gwtplatform:gwtp-mvp-shared:jar:1.4
  gwtp_velocity: org.apache.velocity:velocity:jar:1.7
  gwtp_velocity_deps: commons-lang:commons-lang:jar:2.4
