<% user_code = ENV['USER'] %>
<% prefix = "#{user_code}_" %>
devhost: &devhost
  username: stock-dev
  password: letmein
  host: <%= ENV['DB_SERVER_HOST'] || '127.0.0.1' %>
  port: <%= ENV['DB_SERVER_PORT'] || '5432' %>

development:
  database: <%= prefix %>SCOUTMGR_DEV
  <<: *devhost

test:
  database: <%= prefix %>SCOUTMGR_TEST
  <<: *devhost

import:
  database: PROD_CLONE_SCOUTMGR
  <<: *devhost
